// Search aliases per category. Lets the user type "food" / "restaurant" /
// "dinner" and still surface a transaction (or perk) tagged as `dining_out`.
// Aliases are intentionally redundant — a single keyword can map to multiple
// categories if the relationship is real (e.g. "travel" hits flights, hotels,
// AND the travel category proper), so when a category's haystack is enriched
// we include words from every related category.

export const CATEGORY_ALIASES: Record<string, string[]> = {
  dining_out: [
    "restaurant", "restaurants", "dining", "diner", "diners", "dinner",
    "lunch", "breakfast", "brunch", "supper", "food", "foods", "eatery",
    "eateries", "bistro", "cafe", "cafes", "cafeteria", "buffet", "takeout",
    "takeaway", "delivery", "doordash", "ubereats", "grubhub", "postmates",
    "seamless", "pizza", "burger", "burgers", "sushi", "ramen", "thai",
    "chinese", "italian", "mexican", "indian", "japanese", "korean",
    "vietnamese", "fastfood", "fast", "drive thru", "drivethru", "dine",
    "dine out", "eat", "eat out", "eating", "feast", "meal", "meals",
    "snack", "snacks", "bakery", "deli", "bbq", "barbecue", "steakhouse",
    "tacos", "noodles", "pho", "kabob",
  ],
  groceries: [
    "grocery", "groceries", "supermarket", "supermarkets", "market", "markets",
    "produce", "fresh", "vegetables", "veggies", "fruit", "fruits", "meat",
    "butcher", "deli", "dairy", "milk", "cheese", "eggs", "bread", "snacks",
    "pantry", "kitchen", "cooking", "ingredients", "bulk", "wholefoods",
    "whole foods", "trader joes", "traderjoes", "kroger", "safeway", "albertsons",
    "publix", "wegmans", "aldi", "costco", "sams", "sam's club", "samsclub",
    "walmart grocery", "instacart", "shipt", "amazon fresh", "amazonfresh",
    "shopping list", "weekly shop", "groccery", "grocer",
  ],
  gas: [
    "gas", "gasoline", "petrol", "fuel", "diesel", "unleaded", "premium",
    "regular", "octane", "fillup", "fill up", "fill-up", "tank", "pump",
    "pumps", "station", "stations", "gasstation", "gas station", "service station",
    "shell", "chevron", "exxon", "mobil", "bp", "76", "arco", "valero",
    "sunoco", "marathon", "speedway", "circle k", "circlek", "wawa",
    "sheetz", "costco gas", "sams gas", "shellv", "petroleum", "refuel",
    "filling", "topup", "top up", "top-up", "ev", "evcharging",
  ],
  ev_charging: [
    "ev", "ev charging", "evcharging", "electric", "electric vehicle",
    "tesla", "supercharger", "super charger", "chargepoint", "charge point",
    "evgo", "ev go", "electrify america", "blink", "tesla charge",
    "kw", "kwh", "fast charge", "level 2", "level 3", "dcfc", "plug",
    "plugin", "plug in", "charging station", "chargingstation",
    "battery", "current", "amp", "volts", "voltage", "supercharge",
  ],
  rideshare: [
    "uber", "lyft", "rideshare", "ride share", "ride", "rides", "cab",
    "cabs", "taxi", "taxis", "yellow cab", "via", "ola", "didi", "grab",
    "rideshare credit", "uber eats", "ubereats", "lyft pink", "uber one",
    "uberone", "shuttle", "limo", "town car", "car service", "carservice",
    "chauffeur", "driver", "pickup", "drop off", "dropoff", "lift",
    "uber x", "uberx", "lyft line", "lyftline", "share ride",
    "carpool", "kart", "transport",
  ],
  public_transit: [
    "transit", "public transit", "publictransit", "subway", "metro",
    "tube", "underground", "train", "trains", "rail", "amtrak", "bart",
    "mta", "wmata", "septa", "marta", "cta", "muni", "lirr", "njt",
    "metro card", "metrocard", "clipper", "presto", "fare", "fares",
    "ticket", "tickets", "monthly pass", "transit pass", "bus", "buses",
    "tram", "trolley", "ferry", "commuter", "commute", "subway pass",
    "rail pass", "transitcheck",
  ],
  parking: [
    "parking", "park", "garage", "lot", "meter", "meters", "spotpark",
    "spot", "valet", "parkmobile", "park mobile", "parkwhiz", "park whiz",
    "spothero", "spot hero", "meter maid", "ticket", "violation",
    "parking ticket", "permit", "parking permit", "valet parking",
    "lot fee", "garage fee", "deck", "structure", "stall",
    "parkingfee", "lotfee", "metered",
  ],
  travel: [
    "travel", "trip", "trips", "vacation", "vacay", "holiday", "holidays",
    "getaway", "journey", "tour", "tours", "expedition", "excursion",
    "abroad", "international", "domestic", "tourism", "tourist",
    "sightseeing", "adventure", "itinerary", "booking", "reservation",
    "expedia", "kayak", "priceline", "orbitz", "booking.com", "hopper",
    "tripadvisor", "trip advisor", "agoda", "trivago", "google travel",
    "capital one travel", "chase travel", "amex travel",
    "flight", "hotel", "rental", "transit", "lodging", "stay",
  ],
  flights: [
    "flight", "flights", "airline", "airlines", "airfare", "airfares",
    "plane", "planes", "airplane", "aircraft", "aviation", "fly", "flying",
    "fly to", "flyto", "boarding pass", "boarding", "ticket", "tickets",
    "delta", "united", "american airlines", "american", "southwest",
    "jetblue", "alaska", "spirit", "frontier", "hawaiian", "lufthansa",
    "british airways", "air france", "klm", "emirates", "qatar",
    "singapore air", "ana", "japan airlines", "jal", "ryanair",
    "easyjet", "wizz", "first class", "business class", "economy",
    "premium economy", "miles", "redemption", "award flight",
  ],
  hotels: [
    "hotel", "hotels", "stay", "stays", "lodging", "accommodation",
    "accommodations", "resort", "resorts", "motel", "motels", "inn",
    "inns", "bnb", "b&b", "bedandbreakfast", "airbnb", "vrbo",
    "homeaway", "booking.com", "marriott", "hilton", "hyatt", "ihg",
    "intercontinental", "holiday inn", "hampton", "courtyard", "westin",
    "sheraton", "double tree", "doubletree", "embassy suites",
    "fairmont", "four seasons", "ritz", "ritzcarlton", "ritz-carlton",
    "fhr", "hotel collection", "lifestyle collection", "premier collection",
    "lobby", "checkin", "check in", "check-in", "checkout", "check out",
    "night", "nights", "room", "rooms", "suite",
  ],
  car_maintenance: [
    "car", "auto", "automotive", "automobile", "vehicle", "service",
    "maintenance", "repair", "repairs", "oil change", "oilchange",
    "tire", "tires", "brake", "brakes", "battery", "alignment",
    "inspection", "smog", "emission", "tune up", "tuneup", "tune-up",
    "mechanic", "garage", "shop", "auto shop", "autoshop", "jiffy lube",
    "jiffylube", "valvoline", "midas", "pep boys", "pepboys", "firestone",
    "goodyear", "discount tire", "discounttire", "carwash", "car wash",
    "detail", "detailing",
  ],
  streaming: [
    "streaming", "stream", "netflix", "hulu", "disney+", "disney plus",
    "disneyplus", "hbo", "max", "hbomax", "hbo max", "prime video",
    "primevideo", "amazon prime", "apple tv", "appletv", "apple tv+",
    "appletv+", "paramount+", "paramount plus", "peacock", "youtube",
    "youtube tv", "youtubetv", "youtube premium", "youtubepremium",
    "spotify", "apple music", "applemusic", "tidal", "pandora",
    "deezer", "soundcloud", "audible", "audiobook", "audiobooks",
    "podcast", "podcasts", "kindle unlimited", "kindleunlimited",
    "tv", "movie", "movies", "show", "shows", "binge", "watch",
    "subscription", "video", "music", "entertainment",
  ],
  software: [
    "software", "saas", "subscription", "license", "license fee",
    "1password", "lastpass", "dropbox", "google one", "icloud",
    "microsoft 365", "office 365", "office", "adobe", "creative cloud",
    "creativecloud", "figma", "notion", "linear", "github", "vercel",
    "netlify", "aws", "gcp", "azure", "digitalocean", "heroku",
    "supabase", "firebase", "cloudflare", "datadog", "sentry",
    "vscode", "cursor", "jetbrains", "intellij", "evernote",
    "rescuetime", "todoist", "things", "anki",
  ],
  ai_tools: [
    "ai", "ai tools", "aitools", "claude", "chatgpt", "openai",
    "anthropic", "gemini", "google ai", "perplexity", "midjourney",
    "stable diffusion", "stablediffusion", "runway", "github copilot",
    "copilot", "cursor", "replicate", "huggingface", "hugging face",
    "llm", "model", "chatbot", "assistant", "automation", "agent",
    "ml", "machine learning", "machinelearning", "neural", "embedding",
    "vector", "rag", "fine tune", "finetune", "fine-tune", "training",
    "inference",
  ],
  cloud_storage: [
    "cloud", "storage", "icloud", "google drive", "googledrive",
    "google one", "googleone", "dropbox", "onedrive", "one drive",
    "box", "mega", "pcloud", "tresorit", "sync.com", "sync com",
    "backup", "backups", "files", "drive", "vault", "archive",
    "photos", "google photos", "googlephotos", "amazon photos",
    "amazonphotos", "icloud+", "icloudplus", "200gb", "2tb", "tb",
  ],
  shopping: [
    "shopping", "shop", "store", "stores", "retail", "retailer",
    "purchase", "purchases", "buy", "bought", "amazon", "amzn",
    "ebay", "etsy", "target", "walmart", "costco", "sam's", "sams",
    "best buy", "bestbuy", "macy's", "macys", "nordstrom", "kohls",
    "tjmaxx", "tj maxx", "marshalls", "homegoods", "home goods",
    "ross", "burlington", "online", "ecommerce", "e-commerce",
    "checkout", "cart", "order", "orders",
  ],
  clothing: [
    "clothing", "clothes", "apparel", "outfit", "outfits", "fashion",
    "wear", "shirt", "shirts", "pants", "trousers", "jeans", "dress",
    "dresses", "skirt", "skirts", "shoes", "sneakers", "boots",
    "jacket", "coat", "coats", "sweater", "hoodie", "tshirt", "t-shirt",
    "blouse", "suit", "tie", "socks", "underwear", "lingerie",
    "uniqlo", "h&m", "hm", "zara", "gap", "old navy", "oldnavy",
    "banana republic", "bananarepublic", "br", "j.crew", "jcrew",
    "anthropologie", "aritzia", "lululemon", "athleta", "patagonia",
    "north face", "northface", "nike", "adidas", "ssense", "ssense",
  ],
  electronics: [
    "electronics", "electronic", "gadget", "gadgets", "tech", "device",
    "devices", "phone", "phones", "smartphone", "iphone", "android",
    "samsung", "google pixel", "pixel", "laptop", "laptops", "computer",
    "computers", "macbook", "imac", "desktop", "tablet", "ipad",
    "kindle", "monitor", "monitors", "display", "tv", "television",
    "headphones", "earbuds", "airpods", "speaker", "speakers",
    "camera", "cameras", "lens", "drone", "drones", "console",
    "playstation", "ps5", "xbox", "switch", "nintendo", "gpu", "cpu",
    "ssd", "ram", "memory", "charger", "cable", "adapter", "best buy",
  ],
  entertainment: [
    "entertainment", "fun", "leisure", "movie", "movies", "cinema",
    "theater", "theatre", "concert", "concerts", "show", "shows",
    "play", "plays", "musical", "broadway", "ticket", "tickets",
    "ticketmaster", "stubhub", "stub hub", "seatgeek", "seat geek",
    "axs", "live nation", "livenation", "venue", "amphitheater",
    "comedy", "club", "festival", "festivals", "fair", "event",
    "events", "amusement", "park", "theme park", "themepark", "disney",
    "universal", "six flags", "sixflags", "carnival", "circus",
    "museum", "gallery", "exhibit", "ballet", "opera", "symphony",
  ],
  games: [
    "game", "games", "gaming", "videogame", "video game", "videogames",
    "video games", "steam", "epic", "epic games", "epicgames", "gog",
    "playstation", "ps5", "ps store", "psn", "xbox", "xbox live",
    "xboxlive", "game pass", "gamepass", "nintendo", "switch", "eshop",
    "twitch", "discord", "battle.net", "battlenet", "blizzard",
    "ea", "ubisoft", "rockstar", "roblox", "fortnite", "minecraft",
    "console", "controller", "joystick", "headset", "esports",
    "tournament", "league", "guild", "raid",
  ],
  health: [
    "health", "healthcare", "medical", "medicine", "doctor", "doctors",
    "physician", "clinic", "hospital", "er", "emergency", "urgent care",
    "urgentcare", "appointment", "checkup", "physical", "exam", "tests",
    "lab", "labs", "labwork", "lab work", "xray", "x-ray", "mri",
    "ct scan", "ctscan", "ultrasound", "vaccine", "vaccination", "shot",
    "shots", "immunization", "specialist", "primary care", "primarycare",
    "pcp", "kaiser", "anthem", "blue cross", "bluecross", "aetna",
    "cigna", "united healthcare", "uhc", "copay", "deductible",
    "coinsurance", "premium", "wellness", "checkup", "rx",
  ],
  pharmacy: [
    "pharmacy", "pharmacies", "drugstore", "drug store", "drugstores",
    "drug stores", "rx", "prescription", "prescriptions", "meds",
    "medication", "medications", "medicine", "pills", "cvs", "walgreens",
    "rite aid", "riteaid", "duane reade", "duanereade", "wal mart pharmacy",
    "walmart pharmacy", "target pharmacy", "costco pharmacy", "kaiser pharmacy",
    "otc", "over the counter", "overthecounter", "tylenol", "advil",
    "ibuprofen", "vitamin", "vitamins", "supplements", "first aid",
    "firstaid", "bandage", "bandaid", "thermometer",
  ],
  gym: [
    "gym", "gyms", "fitness", "workout", "workouts", "exercise",
    "training", "trainer", "personal trainer", "personaltrainer",
    "yoga", "pilates", "barre", "spin", "spinning", "cycling",
    "soulcycle", "soul cycle", "peloton", "crossfit", "cross fit",
    "boxing", "muay thai", "muaythai", "kickboxing", "martial arts",
    "martialarts", "bjj", "jiu jitsu", "jiujitsu", "tennis", "racquetball",
    "swim", "swimming", "pool", "lap", "laps", "treadmill", "elliptical",
    "weights", "strength", "cardio", "equinox", "lifetime", "life time",
    "lifefitness", "ymca", "lifetime fitness", "blink", "anytime",
    "anytime fitness", "planet fitness", "planetfitness", "la fitness",
    "lafitness", "membership", "monthly", "class pass", "classpass",
  ],
  housing: [
    "housing", "house", "home", "apartment", "apt", "condo", "condos",
    "townhouse", "townhome", "rent", "rental", "lease", "leasing",
    "landlord", "tenant", "mortgage", "loan", "down payment", "downpayment",
    "escrow", "hoa", "association", "property", "property tax",
    "propertytax", "real estate", "realestate", "realtor", "broker",
    "zillow", "redfin", "trulia", "open house", "openhouse", "showing",
    "deposit", "security deposit", "securitydeposit",
  ],
  utilities: [
    "utility", "utilities", "electric", "electricity", "power", "energy",
    "gas bill", "gasbill", "natural gas", "naturalgas", "water", "sewer",
    "sewage", "trash", "garbage", "recycling", "refuse", "waste",
    "pge", "pg&e", "edison", "socal", "socalgas", "con ed", "coned",
    "duke energy", "dominion", "national grid", "nationalgrid",
    "electricity bill", "water bill", "waterbill", "monthly bill",
  ],
  internet: [
    "internet", "wifi", "wi-fi", "broadband", "fiber", "cable internet",
    "comcast", "xfinity", "spectrum", "att", "at&t", "verizon fios",
    "verizonfios", "fios", "google fiber", "googlefiber", "starlink",
    "frontier", "centurylink", "cox", "isp", "modem", "router",
    "ethernet", "speed", "gigabit", "mbps", "data", "bandwidth",
    "service", "monthly internet", "internet bill", "internetbill",
  ],
  phone: [
    "phone", "mobile", "cell", "cellphone", "cellular", "wireless",
    "att", "at&t", "verizon", "tmobile", "t-mobile", "sprint",
    "mint mobile", "mintmobile", "us mobile", "usmobile", "google fi",
    "googlefi", "cricket", "metro", "metropcs", "boost", "tracfone",
    "phone bill", "phonebill", "data plan", "dataplan", "minutes",
    "text", "texts", "sms", "service", "carrier", "plan", "monthly",
    "international", "roaming",
  ],
  income: [
    "income", "earned", "earning", "earnings", "paycheck", "pay",
    "salary", "wage", "wages", "compensation", "comp", "deposit",
    "direct deposit", "directdeposit", "dd", "payroll", "payday",
    "payroll deposit", "stipend", "1099", "w2", "w-2", "biweekly",
    "bi-weekly", "monthly pay", "annual", "raise", "promotion",
    "earnings deposit",
  ],
  bonus: [
    "bonus", "bonuses", "annual bonus", "performance bonus", "spot bonus",
    "spotbonus", "signon", "sign on", "sign-on", "signon bonus",
    "signing bonus", "signingbonus", "retention", "retention bonus",
    "rsu", "rsus", "stock", "equity", "vest", "vesting", "vested",
    "espp", "espp purchase", "stock purchase", "stockpurchase", "options",
    "exercise", "stock options", "stockoptions", "incentive", "ltip",
    "merit", "merit increase",
  ],
  interest_income: [
    "interest", "interest paid", "interest earned", "interestearned",
    "savings interest", "checking interest", "apy", "apr", "yield",
    "high yield", "highyield", "money market", "moneymarket", "mma",
    "cd", "certificate", "certificate of deposit", "treasuries",
    "treasury", "tbill", "t-bill", "tnote", "t-note", "tbond", "t-bond",
    "i bond", "ibond", "i-bond", "bond", "bonds", "fixed income",
    "fixedincome", "coupon", "interest rate",
  ],
  dividend_income: [
    "dividend", "dividends", "div", "qualified dividend", "qualifieddividend",
    "ordinary dividend", "ordinarydividend", "etf", "fund", "mutual fund",
    "mutualfund", "vanguard", "fidelity", "schwab", "blackrock", "voo",
    "vti", "spy", "qqq", "schd", "vym", "reit", "reits", "stock",
    "stocks", "share", "shares", "payout", "distribution", "yield",
    "dividend yield", "dividendyield", "drip", "reinvest", "reinvestment",
  ],
  refund: [
    "refund", "refunds", "return", "returns", "credit", "credited",
    "reimbursement", "reimbursed", "rebate", "rebates", "cashback",
    "cash back", "cash-back", "statement credit", "statementcredit",
    "money back", "moneyback", "chargeback", "charge back", "dispute",
    "disputed", "reversal", "reversed", "adjustment", "correction",
    "store credit", "storecredit", "voucher", "gift card", "giftcard",
  ],
  bank_fee: [
    "fee", "fees", "charge", "charges", "service charge", "servicecharge",
    "monthly fee", "monthlyfee", "maintenance fee", "maintenancefee",
    "atm fee", "atmfee", "out of network", "outofnetwork", "ofn",
    "overdraft", "od fee", "odfee", "nsf", "non sufficient", "insufficient",
    "returned check", "returnedcheck", "bounce", "bounced", "wire fee",
    "wirefee", "transfer fee", "transferfee", "foreign transaction",
    "foreigntransaction", "ftf", "currency conversion", "conversion fee",
    "annual fee", "annualfee", "membership fee", "membershipfee",
    "late fee", "latefee", "late payment", "latepayment", "stop payment",
    "stoppayment", "paper statement", "paperstatement",
  ],
  interest_charged: [
    "interest charged", "interestcharged", "interest charge", "finance charge",
    "financecharge", "apr", "purchase apr", "balance transfer apr",
    "cash advance apr", "cashadvanceapr", "cash advance", "cashadvance",
    "carry balance", "carrying balance", "revolving", "revolved",
    "minimum payment", "minimumpayment", "min payment", "minpayment",
    "billing cycle", "billingcycle", "compound interest", "compoundinterest",
  ],
  insurance: [
    "insurance", "insurer", "policy", "policies", "premium", "deductible",
    "claim", "claims", "auto insurance", "autoinsurance", "car insurance",
    "carinsurance", "geico", "progressive", "state farm", "statefarm",
    "allstate", "liberty mutual", "libertymutual", "farmers", "usaa",
    "amica", "esurance", "renters insurance", "rentersinsurance",
    "homeowners", "homeowners insurance", "homeownersinsurance",
    "life insurance", "lifeinsurance", "term life", "termlife",
    "umbrella", "umbrella policy", "umbrellapolicy", "pet insurance",
    "petinsurance", "trupanion", "lemonade",
  ],
  investment: [
    "investment", "investments", "invest", "investing", "brokerage",
    "vanguard", "fidelity", "schwab", "etrade", "e-trade", "robinhood",
    "webull", "tdameritrade", "td ameritrade", "merrill", "morgan stanley",
    "morganstanley", "stocks", "etf", "etfs", "index fund", "indexfund",
    "mutual fund", "mutualfund", "401k", "401(k)", "403b", "403(b)",
    "ira", "roth", "roth ira", "rothira", "trad ira", "sep ira",
    "hsa", "529", "529 plan", "wealthfront", "betterment", "acorns",
    "stash", "deposit", "contribution", "buy", "sell", "trade", "trades",
  ],
  charity: [
    "charity", "charities", "donate", "donation", "donations", "donated",
    "give", "giving", "gift", "tithe", "tithing", "offering", "alms",
    "nonprofit", "non-profit", "non profit", "501c3", "501(c)(3)",
    "fundraiser", "fundraising", "gofundme", "kickstarter", "patreon",
    "redcross", "red cross", "salvation army", "salvationarmy",
    "unicef", "wwf", "doctors without borders", "doctorswithoutborders",
    "dwb", "msf", "wikimedia", "wikipedia", "givewell", "give directly",
    "givedirectly", "effective altruism", "ea", "tax deductible",
    "taxdeductible",
  ],
  tax: [
    "tax", "taxes", "irs", "income tax", "incometax", "sales tax",
    "salestax", "state tax", "statetax", "federal tax", "federaltax",
    "property tax", "propertytax", "estimated tax", "estimatedtax",
    "quarterly", "quarterly tax", "quarterlytax", "1040", "1040ez",
    "w2", "w-2", "1099", "1099-misc", "1099misc", "1099-int",
    "1099int", "1099-div", "1099div", "tax payment", "taxpayment",
    "turbotax", "turbo tax", "hr block", "h&r block", "hrblock",
    "freetaxusa", "free tax usa", "tax prep", "taxprep", "tax filing",
    "taxfiling", "withholding", "ftb", "franchise tax",
  ],
  cc_payment: [
    "credit card payment", "cardpayment", "card payment", "cc payment",
    "ccpayment", "credit card", "creditcard", "cc", "payment to card",
    "auto pay", "autopay", "auto-pay", "schedule payment", "scheduledpayment",
    "minimum payment", "minimumpayment", "min pay", "balance pay",
    "statement balance", "statementbalance", "current balance",
    "currentbalance", "pay credit", "paycredit", "pay card", "paycard",
    "transfer to card", "transfertocard", "balance transfer",
    "balancetransfer",
  ],
  transfer: [
    "transfer", "transfers", "move", "moved", "moving", "send",
    "sent", "sending", "receive", "received", "deposit", "withdraw",
    "withdrawal", "ach", "wire", "wires", "zelle", "venmo", "paypal",
    "cashapp", "cash app", "apple cash", "applecash", "google pay",
    "googlepay", "to checking", "tochecking", "to savings", "tosavings",
    "between accounts", "betweenaccounts", "internal transfer",
    "internaltransfer",
  ],
  to_nepal: [
    "nepal", "remit", "remittance", "remit to nepal", "send to nepal",
    "money to nepal", "wire to nepal", "wiretonepal", "ekantipur",
    "kantipur", "wire transfer", "international transfer",
    "internationaltransfer", "western union", "westernunion", "wu",
    "moneygram", "money gram", "remitly", "wise", "transferwise",
    "xoom", "ofx", "worldremit", "world remit", "ria", "exchange",
    "fx", "forex", "rupee", "npr", "kathmandu", "ktm", "biratnagar",
    "pokhara", "lalitpur",
  ],
  remittance: [
    "remittance", "remit", "wire", "wire transfer", "wiretransfer",
    "western union", "westernunion", "wu", "moneygram", "money gram",
    "remitly", "wise", "transferwise", "xoom", "worldremit", "world remit",
    "ria", "ofx", "international transfer", "internationaltransfer",
    "send money", "sendmoney", "money transfer", "moneytransfer",
    "abroad", "overseas", "currency exchange", "currencyexchange",
    "fx", "forex",
  ],
  uncategorized: [
    "uncategorized", "unknown", "other", "misc", "miscellaneous",
  ],
};

/** Returns the alias words for a category id as a single space-joined string,
 * suitable for inclusion in a search haystack. Returns "" when no aliases
 * exist (or input is null), so callers can drop it into an array unconditionally.
 */
export function aliasesFor(categoryId: string | null | undefined): string {
  if (!categoryId) return "";
  const list = CATEGORY_ALIASES[categoryId];
  return list ? list.join(" ") : "";
}
